// #define DEBUG_MODE

// #define _DEBUG 7
// #define RUN_TESTS

#undef MAX_PLAYERS
    #define MAX_PLAYERS (50)

// Set to true if table aren't set up.
#define SETUP_TABLE 			(true)

// MySQL Prepared Statement
#define MYSQL_PREPARE_DEBUG 	(false)
#define MAX_STATEMENTS          100

// Server Settings
#define SERVER_NAME 			"Southwood Roleplay"
#define SERVER_ALIAS            "SWRP"
#define SERVER_MODE 			"Roleplay"
#define SERVER_LANGUAGE			"Thai"
#define SERVER_WEBSITE			"sw-rp.com"

#define SCRIPT_VERSION_MAJOR	1
#define SCRIPT_VERSION_MINOR	1
#define SCRIPT_VERSION_PATCH	0

// BCrypt
#define BCRYPT_COST 12

// MySQL
#define MYSQL_CHARSET           "tis620"

// Discord
#define USING_DISCORD